# Data CLeaning

In [18]:
import pandas as pd

### Extract CSVs into DataFrames

In [19]:
# Name of CSV file
file = "../Resources/covid_cases.csv"

#Read CSV
case_df = pd.read_csv(file, encoding="UTF-8")
case_df.head()

,State/Territory,Total Cases,Confirmed Cases,Probable Cases,Cases in Last 7 Days,Case Rate per 100000,Total Deaths,Confirmed Deaths,Probable Deaths,Deaths in Last 7 Days,...,% Positive Last 30 Days,% Positive Last 7 Days,# Tests per 100K,Total # Tests,# Tests per 100K Last 7 Days,Total # Tests Last 7 Days,# Tests per 100K Last 30 Days,Total # Tests Last 30 Days,New Cases,New Deaths
0,Alabama,1333137.0,957838.0,375299.0,8836.0,27189.0,19696.0,15118.0,4578.0,1.0,...,10-14.9%,15-19.9%,157918.0223,7771986.0,464.41,22856.0,2289.67,112687.0,1463.0,0.0
1,Alaska,257263.0,0.0,0.0,1838.0,35167.0,1252.0,NaN,NaN,0.0,...,10-14.9%,10-14.9%,569912.1120,4166958.0,369.96,2705.0,1992.18,14566.0,1838.0,0.0
2,American Samoa,6270.0,0.0,0.0,78.0,13230.0,31.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,Arizona,2093680.0,1845454.0,248226.0,16334.0,28764.0,30400.0,26426.0,3974.0,28.0,...,20-24.9%,20-24.9%,202944.4171,15061319.0,527.89,39177.0,2809.05,208471.0,16334.0,28.0
4,Arkansas,852229.0,0.0,0.0,4418.0,28240.0,11528.0,NaN,NaN,17.0,...,10-14.9%,10-14.9%,159002.2445,4818598.0,607.65,18415.0,2278.78,69059.0,954.0,1.0

In [20]:
# Name of CSV file
file2 = "../Resources/covid_vaccine.csv"

#Read CSV
vaccine_df = pd.read_csv(file2, encoding="UTF-8")
vaccine_df.head()

,State/Territory,Total Doses Distributed,Doses Distributed per 100K,18+ Doses Distributed per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,Percent People Primary Other Booster Other,People with a Second Booster Dose,People 50+ with a Second Booster Dose,Percent of People 50+ with First Booster Dose who Received Second Booster Dose,People 65+ with a Second Booster Dose,Percent of People 65+ with First Booster Dose who Received Second Booster Dose,People with Pfizer Second Booster Dose,People with Moderna Second Booster Dose,People with Janssen Second Booster Dose,People with Second Booster Dose of Other Manufacturer
0,United States,758129055,228346.0,293553.0,592269252,178390.0,535659030,207411.0,259198178,78.1,...,8.3,16832169.0,16022912,25.3,11123046,31.8,8756788,8046534,16422,12425
1,Alaska,1609665,220036.0,291838.0,1171773,160178.0,1048472,190091.0,513559,70.2,...,NaN,NaN,30246,26.0,19111,32.2,15000,17011,47,7
2,Alabama,10035640,204676.0,263066.0,6402751,130584.0,5972815,156566.0,3096313,63.1,...,NaN,NaN,107319,15.8,80439,19.3,50402,61512,216,13
3,Arkansas,6461880,214125.0,278812.0,4333404,143595.0,3954012,170604.0,2030137,67.3,...,NaN,NaN,98072,21.3,74091,26.5,47887,53595,72,81
4,American Samoa,121410,256182.0,387458.0,111347,234949.0,82858,264426.0,45464,95.0,...,NaN,NaN,1030,12.7,478,20.8,842,251,0,0

In [28]:
# Name of CSV file
file3 = "../Resources/states_long_lat.csv"

#Read CSV
states_df = pd.read_csv(file3, encoding="UTF-8")
states_df.head()

  State/Territory   latitude   longitude
0          Alaska  63.588753 -154.493062
1         Alabama  32.318231  -86.902298
2        Arkansas  35.201050  -91.831833
3         Arizona  34.048928 -111.093731
4      California  36.778261 -119.417932

In [31]:
case_df = case_df.merge(states_df,on='State/Territory')
case_df

Empty DataFrame
Columns: [Total Cases, Confirmed Cases, Probable Cases, Cases in Last 7 Days, Case Rate per 100000, Total Deaths, Confirmed Deaths, Probable Deaths, Deaths in Last 7 Days, Death Rate per 100000, 7-Day Cases Rate per 100000, 7-Day Death Rate per 100000, Total % Positive, % Positive Last 30 Days, % Positive Last 7 Days, # Tests per 100K, Total # Tests, # Tests per 100K Last 7 Days, Total # Tests Last 7 Days, # Tests per 100K Last 30 Days, Total # Tests Last 30 Days, New Cases, New Deaths, latitude_x, longitude_x, name_x, latitude_y, longitude_y, name_y, latitude_x, longitude_x, name_x, latitude_y, longitude_y, name_y, latitude_x, longitude_x, latitude_y, longitude_y, State/Territory, latitude, longitude]
Index: []

[0 rows x 42 columns]

### Create new dataframe with select columns

In [5]:
#select columns
file_cases = df1[["State/Territory", "Total Cases", "Cases in Last 7 Days", "Case Rate per 100000", "Total Deaths", "Deaths in Last 7 Days", "Death Rate per 100000", "7-Day Cases Rate per 100000", "7-Day Death Rate per 100000", "New Cases", "New Deaths", "Latitude", "Longitude"]]

In [6]:
file_cases.head()

,State/Territory,Total Cases,Cases in Last 7 Days,Case Rate per 100000,Total Deaths,Deaths in Last 7 Days,Death Rate per 100000,7-Day Cases Rate per 100000,7-Day Death Rate per 100000,New Cases,New Deaths,Latitude,Longitude
0,Alabama,1333137.0,8836.0,27189.0,19696.0,1.0,401.0,180.2,0.0,1463.0,0.0,32.3182,-86.9023
1,Alaska,257263.0,1838.0,35167.0,1252.0,0.0,171.0,251.2,0.0,1838.0,0.0,63.5888,-154.4931
2,American Samoa,6270.0,78.0,13230.0,31.0,0.0,65.0,164.6,0.0,0.0,0.0,14.2710,170.1322
3,Arizona,2093680.0,16334.0,28764.0,30400.0,28.0,417.0,224.4,0.4,16334.0,28.0,34.0489,-111.0937
4,Arkansas,852229.0,4418.0,28240.0,11528.0,17.0,382.0,146.4,0.6,954.0,1.0,35.2011,-91.8318

In [7]:
file_cases.to_csv("../Resources/cleaned_covid_cases.csv", index=False)

In [8]:
file2 = "../Resources/uncleaned_covid_vaccine.csv"

In [9]:
df2 = pd.read_csv(file2, encoding="UTF-8")

In [10]:
df2.head()

,State/Territory/Federal Entity,Total Doses Distributed,Doses Distributed per 100K,18+ Doses Distributed per 100K,Total Doses Administered by State where Administered,Doses Administered per 100k by State where Administered,18+ Doses Administered by State where Administered,18+ Doses Administered per 100K by State where Administered,People with at least One Dose by State of Residence,Percent of Total Pop with at least One Dose by State of Residence,...,People 50+ with a Second Booster Dose,Percent of People 50+ with First Booster Dose who Received Second Booster Dose,People 65+ with a Second Booster Dose,Percent of People 65+ with First Booster Dose who Received Second Booster Dose,People with Pfizer Second Booster Dose,People with Moderna Second Booster Dose,People with Janssen Second Booster Dose,People with Second Booster Dose of Other Manufacturer,Latitude,Longitude
0,United States,758129055,228346.0,293553.0,592269252,178390.0,535659030,207411.0,259198178,78.1,...,16022912,25.3,11123046,31.8,8756788,8046534,16422,12425,32.3182,-86.9023
1,Alaska,1609665,220036.0,291838.0,1171773,160178.0,1048472,190091.0,513559,70.2,...,30246,26.0,19111,32.2,15000,17011,47,7,63.5888,-154.4931
2,Alabama,10035640,204676.0,263066.0,6402751,130584.0,5972815,156566.0,3096313,63.1,...,107319,15.8,80439,19.3,50402,61512,216,13,14.2710,170.1322
3,Arkansas,6461880,214125.0,278812.0,4333404,143595.0,3954012,170604.0,2030137,67.3,...,98072,21.3,74091,26.5,47887,53595,72,81,34.0489,-111.0937
4,American Samoa,121410,256182.0,387458.0,111347,234949.0,82858,264426.0,45464,95.0,...,1030,12.7,478,20.8,842,251,0,0,35.2011,-91.8318

In [11]:
#select columns
file_vaccine = df2[["State/Territory/Federal Entity","Total Doses Distributed","Doses Distributed per 100K", 
                    "Total Doses Administered by State where Administered","Doses Administered per 100k by State where Administered","People Fully Vaccinated by State of Residence"
                    ,"Percent of Total Pop Fully Vaccinated by State of Residence","People 18+ Fully Vaccinated by State of Residence","Percent of 18+ Pop Fully Vaccinated by State of Residence", "Percent of 18+ Pop Fully Vaccinated by State of Residence","People 12+ Fully Vaccinated by State of Residence", "Percent of 12+ Pop Fully Vaccinated by State of Residence", "People 5+ Fully Vaccinated by State of Residence", "Percent of 5+ Pop Fully Vaccinated by State of Residence", "Latitude","Longitude"]]

In [12]:
file_vaccine.to_csv("../Resources/cleaned_covid_vaccine.csv", index=False)